[env]
TERM = "xterm-256color"

[window]
decorations = "None"
dynamic_padding = true

[scrolling]
history = 0

[font]
normal = { family = "JetBrains Mono" }
size = 9

[colors]
cursor = { cursor = "#efe2c1" }

[colors.primary]
foreground = "#efe2c1"
background = "#121212"

[colors.normal]
black = "#121212"
red = "#cc241d"
green = "#98971a"
yellow = "#d79921"
blue = "#458588"
magenta = "#b16286"
cyan = "#689d6a"
white = "#a89984"

[colors.bright]
black = "#928374"
red = "#fb4934"
green = "#b8bb26"
yellow = "#fabd2f"
blue = "#83a598"
magenta = "#d3869b"
cyan = "#8ec07c"
white = "#efe2c1"

[selection]
save_to_clipboard = true
