model = "gpt-5.3-codex"
model_reasoning_effort = "medium"

approval_policy = "untrusted"

[tui]
animations = false
status_line = ["model-with-reasoning", "current-dir", "context-used", "context-window-size", "five-hour-limit", "weekly-limit", "git-branch"]
theme = "gruvbox-dark"

# Profiles
[profiles.safeinteractive]
approval_policy = "untrusted"
sandbox_mode = "read-only"

[profiles.safenoninteractive]
approval_policy = "never"
sandbox_mode = "read-only"

[profiles.lowreasoning]
model_reasoning_effort = "minimal"

[profiles.highreasoning]
model_reasoning_effort = "xhigh"
