# Enable before colour scheme to avoid overwriting my colours.
eval %sh{kak-lsp}

source "%val{config}/colourscheme.kak"

# Options
# Prevent showing changelog on startup
set-option global startup_info_version 10000000000000
set-option global autowrap_column 100
set-option global tabstop 4
set-option global grepcmd "rg --vimgrep"
set-option global autocomplete prompt
set-option global modelinefmt '{{context_info}} {{mode_info}} | %val{bufname} | W:%opt{lsp_diagnostic_warning_count} E:%opt{lsp_diagnostic_error_count} | %opt{filetype} | %val{cursor_line}:%val{cursor_char_column} '

# Keybinds
hook global InsertChar k %{ try %{
  execute-keys -draft hH <a-k>jk<ret> d
  execute-keys -with-hooks <esc>
}}

map global insert <tab> "<tab><a-;>h<a-;>@"
hook global WinSetOption filetype=(go|makefile) %{
    set-option window indentwidth 0
    map window insert <tab> <tab>
}

define-command smart-pairs-after-ret %[
    try %[
        # Check lines ends with {
        execute-keys -draft Hs\{$<ret>
        # Leave and re-enter insert mode to reset whitespace
        execute-keys -with-hooks <ret>}<esc>O
    ] catch %{
        try %{
            execute-keys -draft Hs\($<ret>
            execute-keys -with-hooks <ret>)<esc>O
        } catch %{
            try %{
                execute-keys -draft Hs\[$<ret>
                execute-keys -with-hooks <ret>]<esc>O
            } catch %{
                # -with-hooks to reenable hooks and allow indenting hooks.
                execute-keys -with-hooks <ret>
            }
        }
    }
]

map global insert <ret> '<a-;>:smart-pairs-after-ret<ret>'

hook global WinSetOption filetype=(git-commit|git-rebase|mail) %{
    set-option window autowrap_column 72
    autowrap-enable
}

# Allows me to have a single kak server handling multiple pwd
hook global ModeChange .*:prompt %{
    reset-pwd
}
hook global ClientCreate .* %{
    reset-pwd
}

hook global BufCreate .* %{
    add-highlighter buffer/linenumbers number-lines -relative -separator " "
    add-highlighter buffer/whitespace show-whitespaces -lf "" -tab » -spc " "
}
hook global BufSetOption filetype=man %{
    remove-highlighter buffer/linenumbers
    remove-highlighter buffer/whitespace
}

# Softwrap
add-highlighter global/ wrap -word -indent

define-command -params 1 highlight-word %{
    add-highlighter -override buffer/hl-word regex %arg{1} 0:search
}
alias global hl highlight-word
define-command nohlsearch %{
    remove-highlighter buffer/hl-word
}
alias global noh nohlsearch

# Case insensitive by default, can simply delete the extra lines when case sensitive is wanted.
map global normal / '/(?i)'

map global normal = '|fmt -w $kak_opt_autowrap_column<ret>'

map global user y '<a-|>xsel --input --clipboard<ret>' -docstring 'System clipboard yank'
map global user P '!xsel --output --clipboard<ret>' -docstring 'System clipboard print'
map global user p '<a-!>xsel --output --clipboard<ret>' -docstring 'System clipboard print'
map global user R '|xsel --output --clipboard<ret>' -docstring 'System clipboard replace'

# LSP
hook global WinSetOption filetype=(c|cpp|go|lua|python|rust|zig) %{
    lsp-enable-window
    hook window -group semantic-tokens BufReload .* lsp-semantic-tokens
    hook window -group semantic-tokens NormalIdle .* lsp-semantic-tokens
    hook -once -always window WinSetOption filetype=.* %{
        remove-hooks window semantic-tokens
    }
    set-option global lsp_semantic_tokens %{
        [
            {face="type", token="class"},
            {face="type", token="enum"},
            {face="type", token="struct"},
            {face="type", token="typeAlias"},
            {face="type", token="type"},
        ]
    }
}

map global user q ':lsp-code-actions<ret>' -docstring 'LSP code actions'
map global user k ':lsp-hover<ret>' -docstring 'LSP hover'
map global user r ':lsp-rename-prompt<ret>' -docstring 'LSP rename'

map global normal <c-n> ':lsp-find-error error warning<ret>' -docstring 'Goto next LSP error'
map global normal <c-p> ':lsp-find-error --previous error warning<ret>' -docstring 'Goto previous LSP error'

map global insert <c-k> '<a-;>:signature-help<ret>' -docstring 'Goto previous LSP error'

map global goto d <esc>:lsp-definition<ret> -docstring 'LSP definition'
map global goto r <esc>:lsp-references<ret> -docstring 'LSP references'

map global object f '<a-semicolon>lsp-object Function Method<ret>' -docstring 'LSP function or method'
map global object t '<a-semicolon>lsp-object Class Interface Module Namespace Struct<ret>' -docstring 'LSP class or module'
map global object d '<a-semicolon>lsp-diagnostic-object error warning<ret>' -docstring 'LSP errors and warnings'

define-command signature-help %{
    set-face global Information default,bright-black
    lsp-signature-help
    hook -group once global ModeChange .* %{
        set-face global Information default,default
        remove-hooks global once
    }
}

define-command reset-pwd %{
    cd %val{client_env_PWD}
}

# To avoid dataloss when using a sessions, always warn about modified buffers when closing clients
# to ensure they are not forgotten about.
define-command q-guard %{
    declare-option -hidden str q_guard_modified ""
    evaluate-commands -buffer * %{
        evaluate-commands %sh{
            if [ "$kak_modified" = "true" ]; then
                printf "set-option global q_guard_modified %s\n" "$kak_quoted_bufname"
            fi
        }
    }
    evaluate-commands %sh{
        if [ -n "$kak_opt_q_guard_modified" ]; then
            printf "buffer %s\n" "$kak_quoted_opt_q_guard_modified"
            printf "echo modified buffer: $kak_opt_q_guard_modified\n"
        else
            printf "quit\n"
        fi
    }
}
alias global q q-guard

# quickfix lists
define-command -hidden qf-jump %{
    execute-keys ',;xH'
    evaluate-commands %sh{
        IFS=':' set -- $kak_selection
        file=$1
        row=$2
        col=$3
        try %{
            printf 'edit %s %s %s' "$file" "$row" "$col"
        }
    }
}

define-command -hidden -params 1 qf-list %{
    edit -scratch "*qf list*"
    execute-keys '%d'
    set-register | %arg{1}
    execute-keys '!<ret>'
    map buffer normal <ret> ':qf-jump<ret>'
    # Auto select if only one result
    try %{
        select 2.1,2.1
        # May be an empty line at the end
        execute-keys <a-K>$<ret>gg
    } catch %{
        execute-keys gg
        qf-jump
    }
}

define-command fp -params 1 %{
    qf-list "fd --hidden --exclude .git --type file | fp --filter-scores -e %arg{1}"
}

define-command fd -params 1.. %{
    qf-list "fd --hidden --exclude .git --type file %arg{@}"
}

define-command qf-open %{
    buffer "*qf list*"
}

define-command -params 2 new-diff %{
    edit -scratch "*configs diff*"
    set-option buffer filetype diff
    execute-keys '%d'
    set-register | "diff -u %arg{1} %arg{2}"
    execute-keys "!<ret>"
    map buffer normal <ret> ":diff-jump<ret>"
    map buffer normal <a-ret> ":diff-jump -<ret>"
}

define-command find -docstring "find files" -params 1 %{ edit %arg{1} }
complete-command find shell-script-candidates %{ fd . --type f }

define-command inc-dec-number -params 2 -docstring "
    inc-dec-number OP NUM
    Apply the given operator (usually + or -) and NUM to each selected
    number" %{
    evaluate-commands -save-regs 'c' %{
        # "c" stores the count we want to use (in decimal)
        set-register c %sh{ echo $(( $2 == 0 ? 1 : $2 )) }

        try %{
            # Hex
            execute-keys s (\A|\+|-|(?<=[^0-9]))0[Xx][0-9A-Fa-f]+ <ret>
            execute-keys | "read val; printf '0x%%0*X\n' $((${#val} - 2)) $(($val %arg{1} %reg{c}))" <ret>

        } catch %{
            # Decimal
            execute-keys s (\A|\+|-|(?<=[^0-9]))[1-9][0-9]* <ret>
            execute-keys | "read val; printf '%%d\n' $(($val %arg{1} %reg{c}))" <ret>
        } catch %{
            fail "No numbers found in selection"
        }
    }
}
map global normal <c-a> ':inc-dec-number + 1<ret>'
map global normal <c-x> ':inc-dec-number - 1<ret>'

define-command gdb-breakpoint %{
    evaluate-commands %sh{
        echo "b $kak_bufname:$kak_cursor_line" | xsel --clipboard --input
    }
}

define-command gh-link %{
    evaluate-commands %sh{
        remote=$(git remote get-url upstream 2>/dev/null || git remote get-url origin)

        repo=$(echo "$remote" | sed -n 's#.*github.com[:/]\(.*\)\.git#\1#p')
        [ -z "$repo" ] && { echo "echo -debug 'repo not found'"; exit; }

        file=$kak_bufname
        line=$kak_cursor_line
        url="https://github.com/$repo/blob/master/$file#L$line"
        echo "$url" | xsel --clipboard --input
    }
}

define-command prefix %{
    evaluate-commands %sh{
        output=$(prefix -vor "$kak_selection")
        printf 'info "%s"\n' "$output"
    }
}

hook global BufOpenFile .*\.([^.]+)\.j2$ %{
    set-option buffer filetype %val{match[1]}
}

hook global BufSetOption filetype=rust %{
    set-option buffer makecmd 'cargo build --message-format=short'
    # Will change for other filetypes used by the same server, but the pattern still works for standard make errors.
    set-option global make_error_pattern "^([^:\n]+):(\d+):(?:(\d+):)? error(?:\[.*\])?:([^\n]+)?"
    set-option buffer formatcmd 'rustfmt'
}

hook global BufSetOption filetype=(c|cpp) %{
    set-option buffer lintcmd 'clang-tidy'
    set-option buffer formatcmd 'clang-format -i'

    evaluate-commands %sh{
        if [ -d "cmake-build-debug" ]; then
            echo "set-option buffer makecmd 'make --no-print-directory -j -C cmake-build-debug'"
        else
            echo "set-option buffer makecmd 'make -j'"
        fi
    }
}

hook global BufSetOption filetype=go %{
    set-option buffer formatcmd 'gofmt'
}

hook global BufSetOption filetype=lua %{
#     set-option buffer lintcmd 'selene'
    set-option buffer formatcmd 'stylua -'
}

hook global BufSetOption filetype=python %{
    set-option buffer formatcmd 'ruff format -'
}

hook global BufSetOption filetype=zig %{
    set-option buffer formatcmd 'zig fmt --stdin'
}

hook global BufOpenFile .*\.lus$ %{
    set-option buffer filetype markdown
}
