# Enable before colour scheme to avoid overwriting my colours.
eval %sh{kak-lsp}

source "%val{config}/colourscheme.kak"

# Options
# Prevent showing changelog on startup
set-option global startup_info_version 10000000000000
set-option global autowrap_column 100
set-option global tabstop 4
set-option global grepcmd "rg --vimgrep"
set-option global autocomplete prompt
set-option global modelinefmt '{{context_info}} {{mode_info}} | %val{bufname} | W:%opt{lsp_diagnostic_warning_count} E:%opt{lsp_diagnostic_error_count} | %opt{filetype} | %val{cursor_line}:%val{cursor_char_column} '

# Keybinds
hook global InsertChar k %{ try %{
  execute-keys -draft hH <a-k>jk<ret> d
  execute-keys -with-hooks <esc>
}}

map global insert <tab> "<tab><a-;>h<a-;>@"
hook global WinSetOption filetype=(go|makefile) %{
    set-option window indentwidth 0
    map window insert <tab> <tab>
}

define-command smart-pairs-after-ret %[
    try %[
        # Check previous line ends with {
        execute-keys -draft <esc>s$<ret>
        execute-keys -draft k<a-l><a-l>s\{<ret>
        # Insert temporary . to prevent trailing whitespace getting removed when hitting <ret>
        # -with-hooks to reenable hooks
        execute-keys -with-hooks '.<ret>}<up><right><right><right><right><backspace>'
    ] catch %[
        try %[
            execute-keys -draft <esc>s$<ret>
            execute-keys -draft k<a-l><a-l>s\(<ret>
            execute-keys -with-hooks '.<ret>)<up><right><right><right><right><backspace>'
        ] catch %[
            try %{
                execute-keys -draft <esc>s$<ret>
                execute-keys -draft k<a-l><a-l>s\[<ret>
                execute-keys -with-hooks '.<ret>]<up><right><right><right><right><backspace>'
            }
        ]
    ]
]

map global insert <ret> '<ret><a-;>:smart-pairs-after-ret<ret>'

hook global WinSetOption filetype=(git-commit|git-rebase|mail) %{
    set-option window autowrap_column 72
    autowrap-enable
}

# Allows me to have a single kak server handling multiple pwd
hook global ModeChange .*:prompt %{
    reset-pwd
}
hook global ClientCreate .* %{
    reset-pwd
}

hook global BufCreate .* %{
    add-highlighter buffer/linenumbers number-lines -relative -separator " "
    add-highlighter buffer/whitespace show-whitespaces -lf "" -tab » -spc " "
}
hook global BufSetOption filetype=man %{
    remove-highlighter buffer/linenumbers
    remove-highlighter buffer/whitespace
}

# Softwrap
add-highlighter global/ wrap -word -indent

# Case insensitive by default, can simply delete the extra lines when case sensitive is wanted.
map global normal / '/(?i)'

map global normal = '|fmt -w $kak_opt_autowrap_column<ret>'

map global user y '<a-|>xsel --input --clipboard<ret>' -docstring 'System clipboard yank'
map global user P '!xsel --output --clipboard<ret>' -docstring 'System clipboard print'
map global user p '<a-!>xsel --output --clipboard<ret>' -docstring 'System clipboard print'
map global user R '|xsel --output --clipboard<ret>' -docstring 'System clipboard replace'

# LSP
hook global WinSetOption filetype=(rust|python|go|zig|c|cpp|lua) %{
    lsp-enable-window
}

map global user q ':lsp-code-actions<ret>' -docstring 'LSP code actions'
map global user k ':lsp-hover<ret>' -docstring 'LSP hover'
map global user r ':lsp-rename-prompt<ret>' -docstring 'LSP rename'

map global normal <c-n> ':lsp-find-error error warning<ret>' -docstring 'Goto next LSP error'
map global normal <c-p> ':lsp-find-error --previous error warning<ret>' -docstring 'Goto previous LSP error'

map global insert <c-k> '<a-;>:signature-help<ret>' -docstring 'Goto previous LSP error'

map global goto d <esc>:lsp-definition<ret> -docstring 'LSP definition'
map global goto r <esc>:lsp-references<ret> -docstring 'LSP references'

map global object f '<a-semicolon>lsp-object Function Method<ret>' -docstring 'LSP function or method'
map global object t '<a-semicolon>lsp-object Class Interface Module Namespace Struct<ret>' -docstring 'LSP class or module'
map global object d '<a-semicolon>lsp-diagnostic-object error warning<ret>' -docstring 'LSP errors and warnings'

define-command reset-pwd %{
    cd %val{client_env_PWD}
}

define-command signature-help %{
    set-face global Information default,bright-black
    lsp-signature-help
    hook -group once global ModeChange .* %{
        set-face global Information default,default
        remove-hooks global once
    }
}

# quickfix lists
define-command -hidden qf-jump %{
    exec ',;xH'
    evaluate-commands %sh{
        IFS=':' set -- $kak_selection
        file=$1
        row=$2
        col=$3
        try %{
            printf 'edit %s %s %s' "$file" "$row" "$col"
        }
    }
}

# TODO: have a single command passed in, then validate the command finds files. Consider naming scratch buffer based on command. Remember qf-open stuff.
# TODO: If only one file, automatically enter without creating scratch buffer
define-command -hidden -params 1.. qf-list %{
    reg dquote %sh{
        printf '%s\n' "$@"
    } %arg{@}

    edit -scratch "*qf list*"
    exec '%R;'
    map buffer normal <ret> ':qf-jump<ret>'
}

define-command qf-open %{
    buffer "*qf list*"
}

define-command fp -params 1 %{
    evaluate-commands %sh{
        echo "qf-list $(fd --hidden --exclude .git --type file | fp --filter-scores -e $1 | tr '\n' ' ')"
    }
    exec 'gg'
}

define-command fd -params 1.. %{
    evaluate-commands %sh{
        echo "qf-list $(fd --hidden --exclude .git --type file $@ | tr '\n' ' ')"
    }
    exec 'gg'
}

define-command find -docstring "find files" -params 1 %{ edit %arg{1} }
complete-command find shell-script-candidates %{ fd . --type f }

define-command inc-dec-number -params 2 -docstring "
    inc-dec-number OP NUM
    Apply the given operator (usually + or -) and NUM to each selected
    number" %{
    evaluate-commands -save-regs 'c' %{
        # "c" stores the count we want to use (in decimal)
        set-register c %sh{ echo $(( $2 == 0 ? 1 : $2 )) }

        try %{
            # Hex
            execute-keys s (\A|\+|-|(?<=[^0-9]))0[Xx][0-9A-Fa-f]+ <ret>
            execute-keys | "read val; printf '0x%%0*X\n' $((${#val} - 2)) $(($val %arg{1} %reg{c}))" <ret>

        } catch %{
            # Decimal
            execute-keys s (\A|\+|-|(?<=[^0-9]))[1-9][0-9]* <ret>
            execute-keys | "read val; printf '%%d\n' $(($val %arg{1} %reg{c}))" <ret>
        } catch %{
            fail "No numbers found in selection"
        }
    }
}
map global normal <c-a> ':inc-dec-number + 1<ret>'
map global normal <c-x> ':inc-dec-number - 1<ret>'

define-command gdb-breakpoint %{
    evaluate-commands %sh{
        echo "b $kak_bufname:$kak_cursor_line" | xsel --clipboard --input
    }
}

define-command gh-link %{
    evaluate-commands %sh{
        remote=$(git remote get-url upstream 2>/dev/null || git remote get-url origin)

        repo=$(echo "$remote" | sed -n 's#.*github.com[:/]\(.*\)\.git#\1#p')
        [ -z "$repo" ] && { echo "echo -debug 'repo not found'"; exit; }

        file=$kak_bufname
        line=$kak_cursor_line
        url="https://github.com/$repo/blob/master/$file#L$line"
        echo "$url" | xsel --clipboard --input
    }
}

define-command prefix %{
    evaluate-commands %sh{
        output=$(prefix -vor "$kak_selection")
        escaped=$(printf '%s\n' "$output" | sed 's/\\/\\\\/g; s/"/\\"/g')
        printf 'info "%s"\n' "$escaped"
    }
}

hook global BufOpenFile .*\.([^.]+)\.j2$ %{
    set-option buffer filetype %val{match[1]}
}

hook global BufSetOption filetype=rust %{
    set-option buffer makecmd 'cargo build --message-format=short'
    # Will change for other filetypes used by the same server, but the pattern still works for standard make errors.
    set-option global make_error_pattern "^([^:\n]+):(\d+):(?:(\d+):)? error(?:\[.*\])?:([^\n]+)?"
    set-option buffer formatcmd 'rustfmt'
}

hook global BufSetOption filetype=(c|cpp) %{
    set-option buffer lintcmd 'clang-tidy'
    set-option buffer formatcmd 'clang-format -i'

    evaluate-commands %sh{
        if [ -d "cmake-build-debug" ]; then
            echo "set-option buffer makecmd 'make --no-print-directory -j -C cmake-build-debug'"
        else
            echo "set-option buffer makecmd 'make -j'"
        fi
    }
}

hook global BufSetOption filetype=go %{
    set-option buffer formatcmd 'gofmt'
}

hook global BufSetOption filetype=lua %{
#     set-option buffer lintcmd 'selene'
    set-option buffer formatcmd 'stylua -'
}

hook global BufSetOption filetype=python %{
    set-option buffer formatcmd 'ruff format -'
}

hook global BufSetOption filetype=zig %{
    set-option buffer formatcmd 'zig fmt --stdin'
}

hook global BufOpenFile .*\.lus$ %{
    set-option buffer filetype markdown
}
