#!/bin/sh
# Using external pipe with st, give a dmenu prompt of recent commands,
# allowing the user to copy the output of one.
# By Jaywalker and Luke - modified by Shivix
tmpfile=$(mktemp /tmp/st-cmd-output.XXXXXX)
trap 'rm "$tmpfile"' 0 1 15
sed -n "w $tmpfile"
sed -i 's/\x0//g' "$tmpfile"
prompt="$(grep "\S" "$tmpfile" | tail -n 1 | sed 's/^\s*//')"
chosen="$(grep -F "$prompt" "$tmpfile" | sed '$d' | tac | dmenu -sf "#161616" -sb "#efe2c1" -p "Copy which command's output?" -i -l 10 | sed 's/[^^]/[&]/g; s/\^/\\^/g')"
prompt="$(echo "$prompt" | sed 's/[^^]/[&]/g; s/\^/\\^/g')"
# This will print only the first occurance of chosen
awk "/^$chosen$/{p=1;print;next} p&&/$prompt/{exit};p" "$tmpfile" | sed '$d' | xsel --input --clipboard
