-- Based on https://github.com/ellisonleao/gruvbox.nvim
vim.g.colors_name = "gruvbox"

local colors = {
    bg0 = "#282828",
    bg1 = "#3c3836",
    bg2 = "#504945",
    bg3 = "#665c54",
    bg4 = "#7c6f64",
    fg1 = "#ebdbb2",
    fg4 = "#a89984",
    red = "#fb4934",
    aqua = "#8ec07c",
    blue = "#83a598",
    gray = "#928374",
    green = "#b8bb26",
    orange = "#fe8019",
    purple = "#d3869b",
    yellow = "#fabd2f",
    dark_green = "#4F5431",
    dark_red = "#722529",
}
local groups = {
    { "Boolean", { link = "Constant" } },
    { "Character", { link = "Constant" } },
    { "ColorColumn", { bg = colors.bg1 } },
    { "Comment", { fg = colors.gray } },
    { "Conditional", { fg = colors.red } },
    { "Constant", { fg = colors.purple } },
    { "CurSearch", { link = "IncSearch" } },
    { "CursorColumn", { link = "CursorLine" } },
    { "CursorLine", { bg = colors.bg1 } },
    { "CursorLineNr", { fg = colors.yellow } },
    { "Cursor", { reverse = true } },
    { "Define", { fg = colors.purple } },
    { "Delimiter", { fg = colors.orange } },
    { "DiagnosticError", { fg = colors.red } },
    { "DiagnosticFloatingError", { fg = colors.red } },
    { "DiagnosticFloatingHint", { fg = colors.aqua } },
    { "DiagnosticFloatingInfo", { fg = colors.blue } },
    { "DiagnosticFloatingWarn", { fg = colors.orange } },
    { "DiagnosticHint", { fg = colors.aqua } },
    { "DiagnosticInfo", { fg = colors.blue } },
    { "DiagnosticUnderlineError", { undercurl = true, sp = colors.red } },
    { "DiagnosticUnderlineHint", { undercurl = true, sp = colors.aqua } },
    { "DiagnosticUnderlineInfo", { undercurl = true, sp = colors.blue } },
    { "DiagnosticUnderlineWarn", { undercurl = true, sp = colors.yellow } },
    { "DiagnosticVirtualTextError", { fg = colors.red } },
    { "DiagnosticVirtualTextHint", { fg = colors.aqua } },
    { "DiagnosticVirtualTextInfo", { fg = colors.blue } },
    { "DiagnosticVirtualTextWarn", { fg = colors.yellow } },
    { "DiagnosticWarn", { fg = colors.yellow } },
    { "DiffAdd", { bg = colors.dark_green } },
    { "DiffChange", { bg = nil } },
    { "DiffDelete", { bg = colors.dark_red } },
    { "DiffText", { bg = colors.yellow, fg = colors.bg0 } },
    { "Directory", { fg = colors.blue } },
    { "EndOfBuffer", { link = "NonText" } },
    { "ErrorMsg", { fg = colors.bg0, bg = colors.red, bold = false } },
    { "Exception", { fg = colors.red } },
    { "FinderSeparator", { fg = colors.aqua } },
    { "Float", { link = "Constant" } },
    { "FoldColumn", { fg = colors.gray, bg = nil } },
    { "Folded", { fg = colors.gray, bg = colors.bg1, italic = false } },
    { "Function", { fg = colors.aqua } },
    { "Identifier", { fg = colors.fg1 } },
    { "Include", { fg = colors.purple } },
    { "IncSearch", { fg = colors.orange, bg = colors.bg0, reverse = true } },
    { "Keyword", { fg = colors.red } },
    { "Label", { link = "Keyword" } },
    { "LineNr", { fg = colors.bg4 } },
    { "LspCodeLens", { fg = colors.gray } },
    { "LspInlayHint", { link = "Comment" } },
    { "LspReferenceRead", { fg = colors.yellow } },
    { "LspReferenceText", { fg = colors.yellow } },
    { "LspReferenceWrite", { fg = colors.orange } },
    { "LspSignatureActiveParameter", { link = "Search" } },
    { "Macro", { fg = colors.purple } },
    { "MatchParen", { bg = colors.bg3 } },
    { "MoreMsg", { fg = colors.yellow } },
    { "netrwDir", { fg = colors.yellow } },
    { "netrwExe", { fg = colors.orange } },
    { "netrwSymLink", { fg = colors.purple } },
    { "netrwClassify", { fg = colors.yellow } },
    { "NonText", { fg = colors.bg2 } },
    { "Normal", { fg = colors.fg1 } },
    { "NormalFloat", { fg = colors.fg1 } },
    { "Number", { link = "Constant" } },
    { "Operator", { fg = colors.orange, italic = false } },
    { "Pmenu", { fg = colors.fg1, bg = colors.bg1 } },
    { "PmenuSbar", { bg = colors.bg1 } },
    { "PmenuSel", { fg = colors.bg1, bg = colors.yellow } },
    { "PreCondit", { fg = colors.purple } },
    { "PreProc", { fg = colors.purple } },
    { "Question", { fg = colors.orange } },
    { "QuickFixLine", { fg = colors.yellow } },
    { "Repeat", { link = "Keyword" } },
    { "Search", { fg = colors.yellow, bg = colors.bg0, reverse = true } },
    { "SignColumn", { bg = nil } },
    { "SpecialKey", { fg = colors.fg4 } },
    { "Special", { fg = colors.orange } },
    { "Statement", { fg = colors.red } },
    { "StatusLine", { fg = colors.yellow, bg = "#32302f", reverse = false } },
    { "StatusLineNC", { fg = colors.bg1, bg = colors.fg4, reverse = true } },
    { "StorageClass", { link = "Type" } },
    { "String", { fg = colors.green } },
    { "Structure", { link = "Type" } },
    { "Title", { fg = colors.green } },
    { "Typedef", { link = "Type" } },
    { "Type", { fg = colors.yellow } },
    { "Underlined", { fg = colors.blue, underline = true } },
    { "Visual", { bg = colors.bg3 } },
    { "VisualNOS", { link = "Visual" } },
    { "WarningMsg", { fg = colors.red } },
    { "WinBar", { fg = colors.fg4, bg = colors.bg0 } },
    { "WinBarNC", { fg = colors.fg3, bg = colors.bg1 } },
    { "WinSeparator", { fg = colors.bg3, bg = nil } },
    { "@attribute", { link = "PreProc" } },
    { "@boolean", { link = "Boolean" } },
    { "@character", { link = "Character" } },
    { "@character.special", { link = "SpecialChar" } },
    { "@comment.error", { link = "ErrorMsg" } },
    { "@comment", { link = "Comment" } },
    { "@comment.note", { link = "SpecialComment" } },
    { "@comment.warning", { link = "WarningMsg" } },
    { "@conditional", { link = "Conditional" } },
    { "@constant.builtin", { link = "Constant" } },
    { "@constant", { link = "Constant" } },
    { "@constructor", { link = "Function" } },
    { "@constructor.lua", { fg = colors.orange } },
    { "@diff.delta", { link = "diffChanged" } },
    { "@diff.minus", { link = "diffRemoved" } },
    { "@diff.plus", { link = "diffAdded" } },
    { "@function.builtin", { link = "Function" } },
    { "@function", { link = "Function" } },
    { "@function.macro", { link = "Macro" } },
    { "@keyword.conditional", { link = "Conditional" } },
    { "@keyword.debug", { link = "Debug" } },
    { "@keyword.directive.define", { link = "Define" } },
    { "@keyword.directive", { link = "PreProc" } },
    { "@keyword", { link = "Keyword" } },
    { "@label", { link = "Label" } },
    { "@markup.italic", { italic = true } },
    { "@markup", { fg = colors.fg1 } },
    { "@markup.list.checked", { fg = colors.green } },
    { "@markup.list", { link = "Delimiter" } },
    { "@markup.list.unchecked", { fg = colors.gray } },
    { "@markup.strikethrough", { strikethrough = true } },
    { "@markup.strong", { bold = true } },
    { "@markup.underline", { underline = true } },
    { "@method", { link = "Function" } },
    { "@module", { fg = colors.yellow } },
    { "@namespace", { fg = colors.yellow } },
    { "@number.float", { link = "Float" } },
    { "@number", { link = "Number" } },
    { "@operator", { link = "Operator" } },
    { "@property", { link = "Identifier" } },
    { "@punctuation", { link = "Delimiter" } },
    { "@string.escape", { link = "SpecialChar" } },
    { "@string", { link = "String" } },
    { "@string.regex", { link = "String" } },
    { "@string.regexp", { link = "String" } },
    { "@string.special", { link = "SpecialChar" } },
    { "@string.special.path", { link = "Underlined" } },
    { "@type.builtin", { link = "Type" } },
    { "@type.definition", { link = "Typedef" } },
    { "@type", { link = "Type" } },
    { "@type.qualifier", { link = "Type" } },
    { "@variable.builtin", { link = "Keyword" } },
    { "@variable", { link = "Identifier" } },
    { "@variable.member", { link = "Identifier" } },
    { "@variable.parameter.builtin", { link = "Identifier" } },
    { "@variable.parameter", { link = "Identifier" } },
}

for _, group in ipairs(groups) do
    vim.api.nvim_set_hl(0, group[1], group[2])
end
