[env]
TERM = "xterm-256color"

[window]
decorations = "None"
dynamic_padding = true

[scrolling]
history = 10000

[font]
normal = { family = "JetBrains Mono" }
size = 9

[cursor]
vi_mode_style = { shape = "Block" }

[colors]
cursor = { cursor = "#efe2c1" }
footer_bar = { foreground = "#fabd2f", background = "#2e2e2e"}

[colors.primary]
foreground = "#efe2c1"
background = "#121212"

[colors.normal]
black = "#121212"
red = "#cc241d"
green = "#98971a"
yellow = "#d79921"
blue = "#458588"
magenta = "#b16286"
cyan = "#689d6a"
white = "#a89984"

[colors.bright]
black = "#928374"
red = "#fb4934"
green = "#b8bb26"
yellow = "#fabd2f"
blue = "#83a598"
magenta = "#d3869b"
cyan = "#8ec07c"
white = "#efe2c1"

[colors.search]
matches = { background = "#fabd2f" }
focused_match = { background = "#d79921" }

[selection]
save_to_clipboard = true

[keyboard]
bindings = [
    { key = "Y", mods = "Control|Shift", action = "ToggleViMode" },
    { key = "Y", mods = "Control|Shift", mode = "Vi", action = "ScrollToBottom" },
]
