[terminal]
shell = "fish"

[env]
TERM = "xterm-256color"

[window]
decorations = "None"
dynamic_padding = true

[scrolling]
history = 10000

[font]
normal = { family = "Iosevka" }
size = 9

[colors]
cursor = { cursor = "#efe2c1" }
footer_bar = { foreground = "#fabd2f", background = "#2e2e2e"}

[colors.primary]
foreground = "#efe2c1"
background = "#121212"

[colors.normal]
black = "#121212"
red = "#cc241d"
green = "#98971a"
yellow = "#e99624"
blue = "#458588"
magenta = "#b16286"
cyan = "#689d6a"
white = "#a89984"

[colors.bright]
black = "#2e2e2e"
red = "#fb4934"
green = "#b8bb26"
yellow = "#fabd2f"
blue = "#83a598"
magenta = "#d3869b"
cyan = "#8ec07c"
white = "#efe2c1"

[keyboard]
bindings = [
    { key = "Y", mods = "Alt|Shift", action = "ToggleViMode" },
    { key = "Y", mods = "Alt|Shift", action = "ScrollToTop" },
    { key = "Y", mods = "Alt|Shift", action = "ToggleLineSelection" },
    { key = "Y", mods = "Alt|Shift", action = "ScrollToBottom" },
    { key = "Y", mods = "Alt|Shift", action = "Copy" },
    { key = "Y", mods = "Alt|Shift", action = "ClearSelection" },
    { key = "Y", mods = "Alt|Shift", action = "ToggleViMode" },
    { key = "Y", mods = "Alt|Shift", chars = "paste_editor\n" },

    { key = "P", mods = "Alt|Shift", action = "ToggleViMode" },
    { key = "P", mods = "Alt|Shift", action = "SearchBackward" },
    { key = "P", mods = "Alt|Shift", chars = "^shivix@" },
    { key = "P", mods = "Alt|Shift", action = "SearchConfirm" },
    { key = "P", mods = "Alt|Shift", action = "ToggleLineSelection" },
    { key = "P", mods = "Alt|Shift", action = "SearchNext" },
    { key = "P", mods = "Alt|Shift", action = "Copy" },
    { key = "P", mods = "Alt|Shift", action = "ClearSelection" },
    { key = "P", mods = "Alt|Shift", action = "ToggleViMode" },
    { key = "P", mods = "Alt|Shift", chars = "paste_last_prompt_results\n" },
]
